name: pytest
on: workflow_dispatch

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
            - name: clone repository
              run: |
                 git clone https://github.com/shutsenliu/github-action-python
                 cd github-action-python
            - name: install pytest
              run: pip install pytest
            - name: run pytest
              run: pytest

